use std::{fs, path::PathBuf, process::Command};

struct EmptyManifest;

impl ethos_zero::Manifest for EmptyManifest {
    fn resolve(&self, _: &str) -> Option<ethos_zero::FileLocation> {
        None
    }
}

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let source = fs::read_to_string(root.join("chroma.ethos")).expect("read Chroma Ethos map");
    let file = ethos_zero::FileReader::new(&EmptyManifest)
        .read(&source)
        .expect("read Chroma Ethos map through Protos");
    let rust = ethos_zero::RustEmitter::datomic_library()
        .emit(&file)
        .expect("generate Chroma Datomic library");
    let output = root.join("src/generated.rs");
    fs::write(&output, format!("// @generated by ethos-zero DatomicLibrary from chroma.ethos.\n{rust}\n"))
        .expect("write generated Rust");
    assert!(Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&output)
        .status()
        .expect("run rustfmt")
        .success());
}
