//! Chroma's public data anatomies are authored in Ethos.

use datomic::{Datomic, Text, TextEdge};
use std::{fs, process::Command};

use chroma::generated::{Request, RequestSetTheme, ThemeMode};

struct EmptyManifest;

impl ethos_zero::Manifest for EmptyManifest {
    fn resolve(&self, _: &str) -> Option<ethos_zero::FileLocation> {
        None
    }
}

fn regenerated_rust() -> String {
    let source = fs::read_to_string("chroma.ethos").expect("read Chroma Ethos map");
    let file = ethos_zero::FileReader::new(&EmptyManifest).read(&source).expect("read Chroma Ethos map through Protos");
    let rust = ethos_zero::RustEmitter::datomic_library().emit(&file).expect("generate Chroma Datomic library");
    let directory = tempfile::tempdir().expect("create formatting directory");
    fs::copy("rustfmt.toml", directory.path().join("rustfmt.toml")).expect("copy Chroma rustfmt configuration");
    let path = directory.path().join("generated.rs");
    fs::write(&path, format!("// @generated by ethos-zero DatomicLibrary from chroma.ethos.\n{rust}\n"))
        .expect("write generated Rust for formatting");
    assert!(Command::new("rustfmt").args(["--edition", "2024"]).arg(&path).status().expect("run rustfmt").success());
    fs::read_to_string(path).expect("read formatted generated Rust")
}

#[test]
fn committed_generated_rust_matches_the_ethos_datomic_library() {
    assert_eq!(fs::read_to_string("src/generated.rs").expect("read committed Rust"), regenerated_rust());
}

#[test]
fn generated_request_keeps_the_datom_boundary_in_one_anatomy() {
    let request = Text::<Request>::from("SetTheme.{Light}").embody().expect("embody Datom request");

    assert!(matches!(request, Request::SetTheme(RequestSetTheme { mode: ThemeMode::Light })));
    assert_eq!(request.textualize().as_ref(), "SetTheme.{Light}");
}
