// @generated by ethos-zero DatomicLibrary from chroma.ethos.
#![allow(dead_code)]
pub struct RequestSetTheme {
    pub mode: ThemeMode,
}
pub struct RequestSetWarmth {
    pub level: WarmthLevel,
}
pub struct RequestSetWarmthKelvin {
    pub kelvin: i64,
}
pub struct RequestStartWarmthRamp {
    pub target: WarmthLevel,
    pub duration: RampDuration,
}
pub struct RequestStartWarmthRampKelvin {
    pub target: i64,
    pub duration: RampDuration,
}
pub struct RequestSetBrightness {
    pub level: BrightnessLevel,
}
pub struct RequestSetBrightnessPercent {
    pub percent: i64,
}
pub struct RequestStartBrightnessRamp {
    pub target: BrightnessLevel,
    pub duration: RampDuration,
}
pub struct RequestStartBrightnessRampPercent {
    pub target: i64,
    pub duration: RampDuration,
}
pub enum Request {
    SetTheme(RequestSetTheme),
    GetTheme,
    SetWarmth(RequestSetWarmth),
    SetWarmthKelvin(RequestSetWarmthKelvin),
    StartWarmthRamp(RequestStartWarmthRamp),
    StartWarmthRampKelvin(RequestStartWarmthRampKelvin),
    InterruptWarmth,
    GetWarmth,
    SetBrightness(RequestSetBrightness),
    SetBrightnessPercent(RequestSetBrightnessPercent),
    StartBrightnessRamp(RequestStartBrightnessRamp),
    StartBrightnessRampPercent(RequestStartBrightnessRampPercent),
    InterruptBrightness,
    GetBrightness,
    GetState,
    GetSolarClock,
}
impl datomic::Datomic for Request {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SetTheme)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SetTheme(<RequestSetTheme as datomic::Datomic>::embody(&headed.body)?));
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(GetTheme)) {
            return Ok(Self::GetTheme);
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SetWarmth)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SetWarmth(<RequestSetWarmth as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SetWarmthKelvin)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SetWarmthKelvin(<RequestSetWarmthKelvin as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(StartWarmthRamp)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::StartWarmthRamp(<RequestStartWarmthRamp as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(StartWarmthRampKelvin)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::StartWarmthRampKelvin(<RequestStartWarmthRampKelvin as datomic::Datomic>::embody(
                &headed.body,
            )?));
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(InterruptWarmth)) {
            return Ok(Self::InterruptWarmth);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(GetWarmth)) {
            return Ok(Self::GetWarmth);
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SetBrightness)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SetBrightness(<RequestSetBrightness as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SetBrightnessPercent)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SetBrightnessPercent(<RequestSetBrightnessPercent as datomic::Datomic>::embody(
                &headed.body,
            )?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(StartBrightnessRamp)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::StartBrightnessRamp(<RequestStartBrightnessRamp as datomic::Datomic>::embody(
                &headed.body,
            )?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(StartBrightnessRampPercent)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::StartBrightnessRampPercent(
                <RequestStartBrightnessRampPercent as datomic::Datomic>::embody(&headed.body)?,
            ));
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(InterruptBrightness)) {
            return Ok(Self::InterruptBrightness);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(GetBrightness)) {
            return Ok(Self::GetBrightness);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(GetState)) {
            return Ok(Self::GetState);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(GetSolarClock)) {
            return Ok(Self::GetSolarClock);
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::SetTheme(value) => datomic::PortionBuilding::headed(
                stringify!(SetTheme),
                protos::Separator::Period,
                <RequestSetTheme as datomic::Datomic>::portion(value),
            ),
            Self::GetTheme => datomic::PortionBuilding::bare(stringify!(GetTheme)),
            Self::SetWarmth(value) => datomic::PortionBuilding::headed(
                stringify!(SetWarmth),
                protos::Separator::Period,
                <RequestSetWarmth as datomic::Datomic>::portion(value),
            ),
            Self::SetWarmthKelvin(value) => datomic::PortionBuilding::headed(
                stringify!(SetWarmthKelvin),
                protos::Separator::Period,
                <RequestSetWarmthKelvin as datomic::Datomic>::portion(value),
            ),
            Self::StartWarmthRamp(value) => datomic::PortionBuilding::headed(
                stringify!(StartWarmthRamp),
                protos::Separator::Period,
                <RequestStartWarmthRamp as datomic::Datomic>::portion(value),
            ),
            Self::StartWarmthRampKelvin(value) => datomic::PortionBuilding::headed(
                stringify!(StartWarmthRampKelvin),
                protos::Separator::Period,
                <RequestStartWarmthRampKelvin as datomic::Datomic>::portion(value),
            ),
            Self::InterruptWarmth => datomic::PortionBuilding::bare(stringify!(InterruptWarmth)),
            Self::GetWarmth => datomic::PortionBuilding::bare(stringify!(GetWarmth)),
            Self::SetBrightness(value) => datomic::PortionBuilding::headed(
                stringify!(SetBrightness),
                protos::Separator::Period,
                <RequestSetBrightness as datomic::Datomic>::portion(value),
            ),
            Self::SetBrightnessPercent(value) => datomic::PortionBuilding::headed(
                stringify!(SetBrightnessPercent),
                protos::Separator::Period,
                <RequestSetBrightnessPercent as datomic::Datomic>::portion(value),
            ),
            Self::StartBrightnessRamp(value) => datomic::PortionBuilding::headed(
                stringify!(StartBrightnessRamp),
                protos::Separator::Period,
                <RequestStartBrightnessRamp as datomic::Datomic>::portion(value),
            ),
            Self::StartBrightnessRampPercent(value) => datomic::PortionBuilding::headed(
                stringify!(StartBrightnessRampPercent),
                protos::Separator::Period,
                <RequestStartBrightnessRampPercent as datomic::Datomic>::portion(value),
            ),
            Self::InterruptBrightness => datomic::PortionBuilding::bare(stringify!(InterruptBrightness)),
            Self::GetBrightness => datomic::PortionBuilding::bare(stringify!(GetBrightness)),
            Self::GetState => datomic::PortionBuilding::bare(stringify!(GetState)),
            Self::GetSolarClock => datomic::PortionBuilding::bare(stringify!(GetSolarClock)),
        }
    }
}
impl datomic::Datomic for RequestSetTheme {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { mode: <ThemeMode as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.mode)],
        )
    }
}
impl datomic::Datomic for RequestSetWarmth {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { level: <WarmthLevel as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.level)],
        )
    }
}
impl datomic::Datomic for RequestSetWarmthKelvin {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { kelvin: <i64 as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.kelvin)],
        )
    }
}
impl datomic::Datomic for RequestStartWarmthRamp {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            target: <WarmthLevel as datomic::Datomic>::embody(&parts[0usize])?,
            duration: <RampDuration as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.target), datomic::Datomic::portion(&self.duration)],
        )
    }
}
impl datomic::Datomic for RequestStartWarmthRampKelvin {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            target: <i64 as datomic::Datomic>::embody(&parts[0usize])?,
            duration: <RampDuration as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.target), datomic::Datomic::portion(&self.duration)],
        )
    }
}
impl datomic::Datomic for RequestSetBrightness {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { level: <BrightnessLevel as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.level)],
        )
    }
}
impl datomic::Datomic for RequestSetBrightnessPercent {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { percent: <i64 as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.percent)],
        )
    }
}
impl datomic::Datomic for RequestStartBrightnessRamp {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            target: <BrightnessLevel as datomic::Datomic>::embody(&parts[0usize])?,
            duration: <RampDuration as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.target), datomic::Datomic::portion(&self.duration)],
        )
    }
}
impl datomic::Datomic for RequestStartBrightnessRampPercent {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            target: <i64 as datomic::Datomic>::embody(&parts[0usize])?,
            duration: <RampDuration as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.target), datomic::Datomic::portion(&self.duration)],
        )
    }
}
pub struct ReplyTheme {
    pub mode: ThemeMode,
}
pub struct ReplyWarmth {
    pub kelvin: i64,
}
pub struct ReplyBrightness {
    pub percent: i64,
}
pub struct ReplyState {
    pub theme: ThemeMode,
    pub kelvin: i64,
    pub percent: i64,
}
pub struct ReplySolarClock {
    pub utc_offset_seconds: i64,
    pub equation_of_time_valid_until_unix_seconds: i64,
}
pub struct ReplyError {
    pub message: datomic::DatomicString,
}
pub enum Reply {
    Accepted,
    Theme(ReplyTheme),
    Warmth(ReplyWarmth),
    Brightness(ReplyBrightness),
    State(ReplyState),
    SolarClock(ReplySolarClock),
    SolarClockUnavailable,
    Error(ReplyError),
}
impl datomic::Datomic for Reply {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Accepted)) {
            return Ok(Self::Accepted);
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Theme)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Theme(<ReplyTheme as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Warmth)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Warmth(<ReplyWarmth as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Brightness)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Brightness(<ReplyBrightness as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(State)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::State(<ReplyState as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(SolarClock)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::SolarClock(<ReplySolarClock as datomic::Datomic>::embody(&headed.body)?));
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(SolarClockUnavailable)) {
            return Ok(Self::SolarClockUnavailable);
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Error)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Error(<ReplyError as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Accepted => datomic::PortionBuilding::bare(stringify!(Accepted)),
            Self::Theme(value) => datomic::PortionBuilding::headed(
                stringify!(Theme),
                protos::Separator::Period,
                <ReplyTheme as datomic::Datomic>::portion(value),
            ),
            Self::Warmth(value) => datomic::PortionBuilding::headed(
                stringify!(Warmth),
                protos::Separator::Period,
                <ReplyWarmth as datomic::Datomic>::portion(value),
            ),
            Self::Brightness(value) => datomic::PortionBuilding::headed(
                stringify!(Brightness),
                protos::Separator::Period,
                <ReplyBrightness as datomic::Datomic>::portion(value),
            ),
            Self::State(value) => datomic::PortionBuilding::headed(
                stringify!(State),
                protos::Separator::Period,
                <ReplyState as datomic::Datomic>::portion(value),
            ),
            Self::SolarClock(value) => datomic::PortionBuilding::headed(
                stringify!(SolarClock),
                protos::Separator::Period,
                <ReplySolarClock as datomic::Datomic>::portion(value),
            ),
            Self::SolarClockUnavailable => datomic::PortionBuilding::bare(stringify!(SolarClockUnavailable)),
            Self::Error(value) => datomic::PortionBuilding::headed(
                stringify!(Error),
                protos::Separator::Period,
                <ReplyError as datomic::Datomic>::portion(value),
            ),
        }
    }
}
impl datomic::Datomic for ReplyTheme {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { mode: <ThemeMode as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.mode)],
        )
    }
}
impl datomic::Datomic for ReplyWarmth {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { kelvin: <i64 as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.kelvin)],
        )
    }
}
impl datomic::Datomic for ReplyBrightness {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { percent: <i64 as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.percent)],
        )
    }
}
impl datomic::Datomic for ReplyState {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 3usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            theme: <ThemeMode as datomic::Datomic>::embody(&parts[0usize])?,
            kelvin: <i64 as datomic::Datomic>::embody(&parts[1usize])?,
            percent: <i64 as datomic::Datomic>::embody(&parts[2usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.theme),
                datomic::Datomic::portion(&self.kelvin),
                datomic::Datomic::portion(&self.percent),
            ],
        )
    }
}
impl datomic::Datomic for ReplySolarClock {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            utc_offset_seconds: <i64 as datomic::Datomic>::embody(&parts[0usize])?,
            equation_of_time_valid_until_unix_seconds: <i64 as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.utc_offset_seconds),
                datomic::Datomic::portion(&self.equation_of_time_valid_until_unix_seconds),
            ],
        )
    }
}
impl datomic::Datomic for ReplyError {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { message: <datomic::DatomicString as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.message)],
        )
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ThemeMode {
    Dark,
    Light,
}
impl datomic::Datomic for ThemeMode {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Dark)) {
            return Ok(Self::Dark);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Light)) {
            return Ok(Self::Light);
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Dark => datomic::PortionBuilding::bare(stringify!(Dark)),
            Self::Light => datomic::PortionBuilding::bare(stringify!(Light)),
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum WarmthLevel {
    Cold,
    Cool,
    Neutral,
    Warm,
    Warmer,
    Warmest,
}
impl datomic::Datomic for WarmthLevel {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Cold)) {
            return Ok(Self::Cold);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Cool)) {
            return Ok(Self::Cool);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Neutral)) {
            return Ok(Self::Neutral);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Warm)) {
            return Ok(Self::Warm);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Warmer)) {
            return Ok(Self::Warmer);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Warmest)) {
            return Ok(Self::Warmest);
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Cold => datomic::PortionBuilding::bare(stringify!(Cold)),
            Self::Cool => datomic::PortionBuilding::bare(stringify!(Cool)),
            Self::Neutral => datomic::PortionBuilding::bare(stringify!(Neutral)),
            Self::Warm => datomic::PortionBuilding::bare(stringify!(Warm)),
            Self::Warmer => datomic::PortionBuilding::bare(stringify!(Warmer)),
            Self::Warmest => datomic::PortionBuilding::bare(stringify!(Warmest)),
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BrightnessLevel {
    Dim,
    Dimmer,
    Mid,
    Bright,
    Brighter,
    Brightest,
}
impl datomic::Datomic for BrightnessLevel {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Dim)) {
            return Ok(Self::Dim);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Dimmer)) {
            return Ok(Self::Dimmer);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Mid)) {
            return Ok(Self::Mid);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Bright)) {
            return Ok(Self::Bright);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Brighter)) {
            return Ok(Self::Brighter);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Brightest)) {
            return Ok(Self::Brightest);
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Dim => datomic::PortionBuilding::bare(stringify!(Dim)),
            Self::Dimmer => datomic::PortionBuilding::bare(stringify!(Dimmer)),
            Self::Mid => datomic::PortionBuilding::bare(stringify!(Mid)),
            Self::Bright => datomic::PortionBuilding::bare(stringify!(Bright)),
            Self::Brighter => datomic::PortionBuilding::bare(stringify!(Brighter)),
            Self::Brightest => datomic::PortionBuilding::bare(stringify!(Brightest)),
        }
    }
}
pub enum RampDuration {
    Minutes(i64),
    Seconds(i64),
}
impl datomic::Datomic for RampDuration {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Minutes)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Minutes(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Seconds)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Seconds(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Minutes(value) => datomic::PortionBuilding::headed(
                stringify!(Minutes),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
            Self::Seconds(value) => datomic::PortionBuilding::headed(
                stringify!(Seconds),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
        }
    }
}
pub struct Config {
    pub theme: ThemeAxis,
    pub warmth: WarmthAxis,
    pub brightness: BrightnessAxis,
}
impl datomic::Datomic for Config {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 3usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            theme: <ThemeAxis as datomic::Datomic>::embody(&parts[0usize])?,
            warmth: <WarmthAxis as datomic::Datomic>::embody(&parts[1usize])?,
            brightness: <BrightnessAxis as datomic::Datomic>::embody(&parts[2usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.theme),
                datomic::Datomic::portion(&self.warmth),
                datomic::Datomic::portion(&self.brightness),
            ],
        )
    }
}
pub struct ThemeAxis {
    pub concerns: Vec<ThemeConcern>,
    pub palettes: ThemePalettes,
    pub dconf: Option<datomic::DatomicString>,
    pub font_point_size: Option<i64>,
    pub ghostty_config_templates: Option<GhosttyConfigTemplates>,
    pub pi_theme_control: Option<PiThemeControl>,
    pub schedule: ThemeSchedule,
}
impl datomic::Datomic for ThemeAxis {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 7usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            concerns: <Vec<ThemeConcern> as datomic::Datomic>::embody(&parts[0usize])?,
            palettes: <ThemePalettes as datomic::Datomic>::embody(&parts[1usize])?,
            dconf: <Option<datomic::DatomicString> as datomic::Datomic>::embody(&parts[2usize])?,
            font_point_size: <Option<i64> as datomic::Datomic>::embody(&parts[3usize])?,
            ghostty_config_templates: <Option<GhosttyConfigTemplates> as datomic::Datomic>::embody(&parts[4usize])?,
            pi_theme_control: <Option<PiThemeControl> as datomic::Datomic>::embody(&parts[5usize])?,
            schedule: <ThemeSchedule as datomic::Datomic>::embody(&parts[6usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.concerns),
                datomic::Datomic::portion(&self.palettes),
                datomic::Datomic::portion(&self.dconf),
                datomic::Datomic::portion(&self.font_point_size),
                datomic::Datomic::portion(&self.ghostty_config_templates),
                datomic::Datomic::portion(&self.pi_theme_control),
                datomic::Datomic::portion(&self.schedule),
            ],
        )
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ThemeConcern {
    Terminal,
    Desktop,
    Ghostty,
    Pi,
}
impl datomic::Datomic for ThemeConcern {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Terminal)) {
            return Ok(Self::Terminal);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Desktop)) {
            return Ok(Self::Desktop);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Ghostty)) {
            return Ok(Self::Ghostty);
        }
        if datomic::PortionViewing::bare_symbol(portion) == Some(stringify!(Pi)) {
            return Ok(Self::Pi);
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Terminal => datomic::PortionBuilding::bare(stringify!(Terminal)),
            Self::Desktop => datomic::PortionBuilding::bare(stringify!(Desktop)),
            Self::Ghostty => datomic::PortionBuilding::bare(stringify!(Ghostty)),
            Self::Pi => datomic::PortionBuilding::bare(stringify!(Pi)),
        }
    }
}
pub struct ThemePalettes {
    pub dark: ThemePalette,
    pub light: ThemePalette,
}
impl datomic::Datomic for ThemePalettes {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            dark: <ThemePalette as datomic::Datomic>::embody(&parts[0usize])?,
            light: <ThemePalette as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.dark), datomic::Datomic::portion(&self.light)],
        )
    }
}
pub struct ThemePalette {
    pub base00: datomic::DatomicString,
    pub base01: datomic::DatomicString,
    pub base02: datomic::DatomicString,
    pub base03: datomic::DatomicString,
    pub base04: datomic::DatomicString,
    pub base05: datomic::DatomicString,
    pub base06: datomic::DatomicString,
    pub base07: datomic::DatomicString,
    pub base08: datomic::DatomicString,
    pub base09: datomic::DatomicString,
    pub base0_a: datomic::DatomicString,
    pub base0_b: datomic::DatomicString,
    pub base0_c: datomic::DatomicString,
    pub base0_d: datomic::DatomicString,
    pub base0_e: datomic::DatomicString,
    pub base0_f: datomic::DatomicString,
}
impl datomic::Datomic for ThemePalette {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 16usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            base00: <datomic::DatomicString as datomic::Datomic>::embody(&parts[0usize])?,
            base01: <datomic::DatomicString as datomic::Datomic>::embody(&parts[1usize])?,
            base02: <datomic::DatomicString as datomic::Datomic>::embody(&parts[2usize])?,
            base03: <datomic::DatomicString as datomic::Datomic>::embody(&parts[3usize])?,
            base04: <datomic::DatomicString as datomic::Datomic>::embody(&parts[4usize])?,
            base05: <datomic::DatomicString as datomic::Datomic>::embody(&parts[5usize])?,
            base06: <datomic::DatomicString as datomic::Datomic>::embody(&parts[6usize])?,
            base07: <datomic::DatomicString as datomic::Datomic>::embody(&parts[7usize])?,
            base08: <datomic::DatomicString as datomic::Datomic>::embody(&parts[8usize])?,
            base09: <datomic::DatomicString as datomic::Datomic>::embody(&parts[9usize])?,
            base0_a: <datomic::DatomicString as datomic::Datomic>::embody(&parts[10usize])?,
            base0_b: <datomic::DatomicString as datomic::Datomic>::embody(&parts[11usize])?,
            base0_c: <datomic::DatomicString as datomic::Datomic>::embody(&parts[12usize])?,
            base0_d: <datomic::DatomicString as datomic::Datomic>::embody(&parts[13usize])?,
            base0_e: <datomic::DatomicString as datomic::Datomic>::embody(&parts[14usize])?,
            base0_f: <datomic::DatomicString as datomic::Datomic>::embody(&parts[15usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.base00),
                datomic::Datomic::portion(&self.base01),
                datomic::Datomic::portion(&self.base02),
                datomic::Datomic::portion(&self.base03),
                datomic::Datomic::portion(&self.base04),
                datomic::Datomic::portion(&self.base05),
                datomic::Datomic::portion(&self.base06),
                datomic::Datomic::portion(&self.base07),
                datomic::Datomic::portion(&self.base08),
                datomic::Datomic::portion(&self.base09),
                datomic::Datomic::portion(&self.base0_a),
                datomic::Datomic::portion(&self.base0_b),
                datomic::Datomic::portion(&self.base0_c),
                datomic::Datomic::portion(&self.base0_d),
                datomic::Datomic::portion(&self.base0_e),
                datomic::Datomic::portion(&self.base0_f),
            ],
        )
    }
}
pub struct GhosttyConfigTemplates {
    pub dark: datomic::DatomicString,
    pub light: datomic::DatomicString,
}
impl datomic::Datomic for GhosttyConfigTemplates {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            dark: <datomic::DatomicString as datomic::Datomic>::embody(&parts[0usize])?,
            light: <datomic::DatomicString as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.dark), datomic::Datomic::portion(&self.light)],
        )
    }
}
pub struct PiThemeControl {
    pub registry_directory: PiThemeControlRegistryDirectory,
    pub connect_timeout_millis: Option<i64>,
    pub write_timeout_millis: Option<i64>,
}
impl datomic::Datomic for PiThemeControl {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 3usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            registry_directory: <PiThemeControlRegistryDirectory as datomic::Datomic>::embody(&parts[0usize])?,
            connect_timeout_millis: <Option<i64> as datomic::Datomic>::embody(&parts[1usize])?,
            write_timeout_millis: <Option<i64> as datomic::Datomic>::embody(&parts[2usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.registry_directory),
                datomic::Datomic::portion(&self.connect_timeout_millis),
                datomic::Datomic::portion(&self.write_timeout_millis),
            ],
        )
    }
}
pub enum PiThemeControlRegistryDirectory {
    RuntimeRelative(datomic::DatomicString),
    Absolute(datomic::DatomicString),
}
impl datomic::Datomic for PiThemeControlRegistryDirectory {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(RuntimeRelative)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::RuntimeRelative(<datomic::DatomicString as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Absolute)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Absolute(<datomic::DatomicString as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::RuntimeRelative(value) => datomic::PortionBuilding::headed(
                stringify!(RuntimeRelative),
                protos::Separator::Period,
                <datomic::DatomicString as datomic::Datomic>::portion(value),
            ),
            Self::Absolute(value) => datomic::PortionBuilding::headed(
                stringify!(Absolute),
                protos::Separator::Period,
                <datomic::DatomicString as datomic::Datomic>::portion(value),
            ),
        }
    }
}
pub struct ThemeScheduleScheduled {
    pub waypoints: Vec<ThemeWaypoint>,
    pub default: ThemeMode,
}
pub enum ThemeSchedule {
    Manual(ThemeMode),
    Scheduled(ThemeScheduleScheduled),
}
impl datomic::Datomic for ThemeSchedule {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Manual)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Manual(<ThemeMode as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Scheduled)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Scheduled(<ThemeScheduleScheduled as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Manual(value) => datomic::PortionBuilding::headed(
                stringify!(Manual),
                protos::Separator::Period,
                <ThemeMode as datomic::Datomic>::portion(value),
            ),
            Self::Scheduled(value) => datomic::PortionBuilding::headed(
                stringify!(Scheduled),
                protos::Separator::Period,
                <ThemeScheduleScheduled as datomic::Datomic>::portion(value),
            ),
        }
    }
}
impl datomic::Datomic for ThemeScheduleScheduled {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            waypoints: <Vec<ThemeWaypoint> as datomic::Datomic>::embody(&parts[0usize])?,
            default: <ThemeMode as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.waypoints), datomic::Datomic::portion(&self.default)],
        )
    }
}
pub struct ThemeWaypoint {
    pub trigger: RampTrigger,
    pub mode: ThemeMode,
}
impl datomic::Datomic for ThemeWaypoint {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            trigger: <RampTrigger as datomic::Datomic>::embody(&parts[0usize])?,
            mode: <ThemeMode as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.trigger), datomic::Datomic::portion(&self.mode)],
        )
    }
}
pub struct WarmthAxis {
    pub schedule: WarmthSchedule,
}
impl datomic::Datomic for WarmthAxis {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { schedule: <WarmthSchedule as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.schedule)],
        )
    }
}
pub struct WarmthScheduleScheduled {
    pub waypoints: Vec<WarmthWaypoint>,
    pub default: WarmthLevel,
}
pub enum WarmthSchedule {
    Manual(WarmthLevel),
    Scheduled(WarmthScheduleScheduled),
}
impl datomic::Datomic for WarmthSchedule {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Manual)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Manual(<WarmthLevel as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Scheduled)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Scheduled(<WarmthScheduleScheduled as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Manual(value) => datomic::PortionBuilding::headed(
                stringify!(Manual),
                protos::Separator::Period,
                <WarmthLevel as datomic::Datomic>::portion(value),
            ),
            Self::Scheduled(value) => datomic::PortionBuilding::headed(
                stringify!(Scheduled),
                protos::Separator::Period,
                <WarmthScheduleScheduled as datomic::Datomic>::portion(value),
            ),
        }
    }
}
impl datomic::Datomic for WarmthScheduleScheduled {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            waypoints: <Vec<WarmthWaypoint> as datomic::Datomic>::embody(&parts[0usize])?,
            default: <WarmthLevel as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.waypoints), datomic::Datomic::portion(&self.default)],
        )
    }
}
pub struct WarmthWaypoint {
    pub trigger: RampTrigger,
    pub target: WarmthLevel,
    pub ramp_duration: RampDuration,
}
impl datomic::Datomic for WarmthWaypoint {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 3usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            trigger: <RampTrigger as datomic::Datomic>::embody(&parts[0usize])?,
            target: <WarmthLevel as datomic::Datomic>::embody(&parts[1usize])?,
            ramp_duration: <RampDuration as datomic::Datomic>::embody(&parts[2usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.trigger),
                datomic::Datomic::portion(&self.target),
                datomic::Datomic::portion(&self.ramp_duration),
            ],
        )
    }
}
pub struct BrightnessAxis {
    pub schedule: BrightnessSchedule,
}
impl datomic::Datomic for BrightnessAxis {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 1usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self { schedule: <BrightnessSchedule as datomic::Datomic>::embody(&parts[0usize])? })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.schedule)],
        )
    }
}
pub struct BrightnessScheduleScheduled {
    pub waypoints: Vec<BrightnessWaypoint>,
    pub default: BrightnessLevel,
}
pub enum BrightnessSchedule {
    Manual(BrightnessLevel),
    Scheduled(BrightnessScheduleScheduled),
}
impl datomic::Datomic for BrightnessSchedule {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Manual)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Manual(<BrightnessLevel as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Scheduled)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Scheduled(<BrightnessScheduleScheduled as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Manual(value) => datomic::PortionBuilding::headed(
                stringify!(Manual),
                protos::Separator::Period,
                <BrightnessLevel as datomic::Datomic>::portion(value),
            ),
            Self::Scheduled(value) => datomic::PortionBuilding::headed(
                stringify!(Scheduled),
                protos::Separator::Period,
                <BrightnessScheduleScheduled as datomic::Datomic>::portion(value),
            ),
        }
    }
}
impl datomic::Datomic for BrightnessScheduleScheduled {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            waypoints: <Vec<BrightnessWaypoint> as datomic::Datomic>::embody(&parts[0usize])?,
            default: <BrightnessLevel as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.waypoints), datomic::Datomic::portion(&self.default)],
        )
    }
}
pub struct BrightnessWaypoint {
    pub trigger: RampTrigger,
    pub target: BrightnessLevel,
    pub ramp_duration: RampDuration,
}
impl datomic::Datomic for BrightnessWaypoint {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 3usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            trigger: <RampTrigger as datomic::Datomic>::embody(&parts[0usize])?,
            target: <BrightnessLevel as datomic::Datomic>::embody(&parts[1usize])?,
            ramp_duration: <RampDuration as datomic::Datomic>::embody(&parts[2usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![
                datomic::Datomic::portion(&self.trigger),
                datomic::Datomic::portion(&self.target),
                datomic::Datomic::portion(&self.ramp_duration),
            ],
        )
    }
}
pub struct RampTriggerTimeOfDay {
    pub hour: i64,
    pub minute: i64,
}
pub enum RampTrigger {
    Sunrise(i64),
    Sunset(i64),
    CivilDawn(i64),
    CivilDusk(i64),
    TimeOfDay(RampTriggerTimeOfDay),
}
impl datomic::Datomic for RampTrigger {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Sunrise)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Sunrise(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(Sunset)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::Sunset(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(CivilDawn)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::CivilDawn(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(CivilDusk)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::CivilDusk(<i64 as datomic::Datomic>::embody(&headed.body)?));
        }
        if let Some(headed) = datomic::PortionViewing::headed(portion)
            && headed.head.as_ref() == stringify!(TimeOfDay)
            && headed.separator == protos::Separator::Period
        {
            return Ok(Self::TimeOfDay(<RampTriggerTimeOfDay as datomic::Datomic>::embody(&headed.body)?));
        }
        Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape))
    }
    fn portion(&self) -> protos::Portion {
        match self {
            Self::Sunrise(value) => datomic::PortionBuilding::headed(
                stringify!(Sunrise),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
            Self::Sunset(value) => datomic::PortionBuilding::headed(
                stringify!(Sunset),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
            Self::CivilDawn(value) => datomic::PortionBuilding::headed(
                stringify!(CivilDawn),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
            Self::CivilDusk(value) => datomic::PortionBuilding::headed(
                stringify!(CivilDusk),
                protos::Separator::Period,
                <i64 as datomic::Datomic>::portion(value),
            ),
            Self::TimeOfDay(value) => datomic::PortionBuilding::headed(
                stringify!(TimeOfDay),
                protos::Separator::Period,
                <RampTriggerTimeOfDay as datomic::Datomic>::portion(value),
            ),
        }
    }
}
impl datomic::Datomic for RampTriggerTimeOfDay {
    fn embody(portion: &protos::Portion) -> std::result::Result<Self, datomic::Fault> {
        let Some(parts) = datomic::PortionViewing::structural(portion, protos::StructuralEnclosure::Braced) else {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Shape));
        };
        if parts.len() != 2usize {
            return Err(datomic::PortionViewing::fault(portion, datomic::FaultProblem::Arity));
        }
        Ok(Self {
            hour: <i64 as datomic::Datomic>::embody(&parts[0usize])?,
            minute: <i64 as datomic::Datomic>::embody(&parts[1usize])?,
        })
    }
    fn portion(&self) -> protos::Portion {
        datomic::PortionBuilding::structural(
            "",
            protos::StructuralEnclosure::Braced,
            vec![datomic::Datomic::portion(&self.hour), datomic::Datomic::portion(&self.minute)],
        )
    }
}
